# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs flutter tests"
  lane :run_tests do
    sh("flutter test")
  end

  desc "Submit APK to GooglePlay Internal"
  lane :internal_deploy do
    run_tests
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true,  
    )
    slack(message: 'Internal build updated')
  end

  desc "Deploy a new version to the Google Play"
  lane :production_deploy do
    run_tests
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store
    slack(message: 'Play store build updated')
  end
end
